### PR TITLE
WAZO-1160: use default profile for reverse lookup

### PR DESCRIPTION
**Pull request by bloom1**

### CODE REVIEW

**Comment by fredericlepied** [comment]
Could we add a test that was failing before to validate the change?

**Comment by bloom1** [comment]
> I think we should remove `find_by_incall_id` altogether: it should be replaced with a call to wazo-confd `GET /incall/id` to get the destination user UUID. What do you think @bloom1 ? Do you agree? Is it too big a change of scope? Should we create another ticket for this?

No, I think it's an opportunity to change it now. confd `GET /incall/id` does not return the user UUID though, so we swap one DB call to 2 API calls doing that. Would the best solution be to add the user_uuid field to the incall or to do 2 API calls as it is right now?

**Comment by sduthil** [comment]
It would be best to have only one API call, because the reverse lookup caller id computation directly blocks the call from ringing the destination user, so it must be as short as possible.

I thought `GET /incall/id` did return the user UUID but it only returns the user ID: http://wazo-platform.org/documentation/api/configuration.html#operation/get_incall. New technical ticket then. Can you create it?

**Comment by bloom1** [comment]
Yup, I'll create it. Thanks!

**Pull request merged**
