### PR TITLE
WAZO-2837 Remove six as dep since it is no longer needed in xivo-lib-python

### PR DESCRIPTION
**Pull request by sopelj**
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/113
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/187

### CODE REVIEW

**Review by fblackburn1 — APPROVED** [review]

**Comment by fblackburn1** [comment]
recheck

**Comment by sopelj** [comment]
@fblackburn1 sorry, I think this might also depend on: https://github.com/wazo-platform/xivo-dao/pull/187 which is still in progress. :( Should be done soon though.

**Comment by fblackburn1** [comment]
> @fblackburn1 sorry, I think this might also depend on: [wazo-platform/xivo-dao#187](https://github.com/wazo-platform/xivo-dao/pull/187) which is still in progress. :( Should be done soon though.

No issue, just add the ticket number in the PR name (JIRA will link to both tickets)

**Comment by sopelj** [comment]
recheck (Fixed build in xivo-dao)

**Comment by sopelj** [comment]
recheck changed in xivo-dao

**Comment by sopelj** [comment]
recheck (error running job)

**Comment by sopelj** [comment]
recheck

**Review by fblackburn1 — DISMISSED** [review]

**Comment by sopelj** [comment]
recheck

**Comment by sopelj** [comment]
recheck (ci issue fixed)

**Comment by sopelj** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
