### PR TITLE
remove dialaction linked column

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-On: https://github.com/wazo-platform/sf-jobs/pull/46

### CODE REVIEW

**Comment by bloom1** [comment]
regate

**Comment by fblackburn1** [comment]
regate

**Comment by fblackburn1** [comment]
regate

**Comment by fredericlepied** [comment]
regate

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
regate

**Pull request merged**
