### PR TITLE
Mypy isort

### PR DESCRIPTION
**Pull request by sopelj**

### CODE REVIEW

**Comment by sduthil** [comment]
@sopelj is this PR still relevant? If so, could you rebase it, please?

**Comment by fblackburn1** [comment]
> > @sopelj is this PR still relevant? If so, could you rebase it, please?
> 
> I suppose that depends on if the addition of the tools suggested will be accepted (isort, pyupgrade, and common fixes like remove whitespaces, etc). They were proposed with the initial proposal in Jira and were considered to be "too big of a change". I don't know if that has changed in the months since. Regardless, I rebased and updated the dependencies.

As stated in the jira ticket ([WAZO-2984](https://wazo-dev.atlassian.net/browse/WAZO-2984), the task has been split with [WAZO-3283](https://wazo-dev.atlassian.net/browse/WAZO-3283). After someone do the first step, then we could go forward with this PR

**Comment by sopelj** [comment]
> > > @sopelj is this PR still relevant? If so, could you rebase it, please?
> > 
> > 
> > I suppose that depends on if the addition of the tools suggested will be accepted (isort, pyupgrade, and common fixes like remove whitespaces, etc). They were proposed with the initial proposal in Jira and were considered to be "too big of a change". I don't know if that has changed in the months since. Regardless, I rebased and updated the dependencies.
> 
> As stated in the jira ticket ([WAZO-2984](https://wazo-dev.atlassian.net/browse/WAZO-2984)), the task has been split with [WAZO-3283](https://wazo-dev.atlassian.net/browse/WAZO-3283). When someone will complete the first step, then we could go forward with this PR

What exactly is the "first step"? The sub-proposition has been done in quite a few repos and some have had it for 6-9 months already. Do we have to wait for every repo to be done before we start adding the other tools? I don't think that will happen any time soon. Not every repo even has black and that's been years.

**Comment by fblackburn1** [comment]
> > > > @sopelj is this PR still relevant? If so, could you rebase it, please?
> > > 
> > > 
> > > I suppose that depends on if the addition of the tools suggested will be accepted (isort, pyupgrade, and common fixes like remove whitespaces, etc). They were proposed with the initial proposal in Jira and were considered to be "too big of a change". I don't know if that has changed in the months since. Regardless, I rebased and updated the dependencies.
> > 
> > 
> > As stated in the jira ticket ([WAZO-2984](https://wazo-dev.atlassian.net/browse/WAZO-2984)), the task has been split with [WAZO-3283](https://wazo-dev.atlassian.net/browse/WAZO-3283). When someone will complete the first step, then we could go forward with this PR
> 
> What exactly is the "first step"? The sub-proposition ([WAZO-3283](https://wazo-dev.atlassian.net/browse/WAZO-3283)) has been done in quite a few repos and some have had it for 6-9 months already. Do we have to wait for every repo to be done before we start adding the other tools? I don't think that will happen any time soon. Not every repo even has black and that's been years.

As stated in the ticket, a minimum of all debian packaged repository should be done.
We must minimize divergence between (most used) repos.
If you found a repo without tox or black in the debian packaged repo, please add it asap, it should not exist
If you need help to update some repos, feel free to ask help

**Comment by sopelj** [comment]
> > > > > @sopelj is this PR still relevant? If so, could you rebase it, please?
> > > > 
> > > > 
> > > > I suppose that depends on if the addition of the tools suggested will be accepted (isort, pyupgrade, and common fixes like remove whitespaces, etc). They were proposed with the initial proposal in Jira and were considered to be "too big of a change". I don't know if that has changed in the months since. Regardless, I rebased and updated the dependencies.
> > > 
> > > 
> > > As stated in the jira ticket ([WAZO-2984](https://wazo-dev.atlassian.net/browse/WAZO-2984)), the task has been split with [WAZO-3283](https://wazo-dev.atlassian.net/browse/WAZO-3283). When someone will complete the first step, then we could go forward with this PR
> > 
> > 
> > What exactly is the "first step"? The sub-proposition ([WAZO-3283](https://wazo-dev.atlassian.net/browse/WAZO-3283)) has been done in quite a few repos and some have had it for 6-9 months already. Do we have to wait for every repo to be done before we start adding the other tools? I don't think that will happen any time soon. Not every repo even has black and that's been years.
> 
> As stated in the ticket, a minimum of all debian packaged repository should be done. We must minimize divergence between (most used) repos. But I'm still open to other suggestion to achieve this goal If you found a repo without tox or black in the debian packaged repo, please add it asap, it should not exist If you need help to update some repos, feel free to ask help

This would be ideal, but you know frequently only have time to update repositories other than the ones we are working on. I just think it is a shame to delay improvements just because we have not had time to go through all of the others. It prevents us from making improvements to one or even many. We could already have been taking advantage of this functionality for months, but instead it make take another year or more depending on priorities.

**Comment by fblackburn1** [comment]
> This would be ideal, but you know we frequently only have time to update repositories we are already working on. I just think it is a shame to delay improvements just because we have not had time to go through all of the others. It prevents us from making improvements to one or even many. We could already have been taking advantage of this functionality for months, but instead it make take another year or more depending on priorities.

Not sure to understand your point here
- As wazo contributor, we are free to improve the code we want
  - Developer have at least 0.5-1 free day by week to improve things
- [WAZO-3283](https://wazo-dev.atlassian.net/browse/WAZO-3283) should take 2-3 days
- This split decision was discussed and agreed by many developers to minimize divergence
-  If no developer made it a priority, than maybe this functionality is not so much important for them

But again, if you have better way to avoid desync between repo and keep consistency. Maybe a wpep of how to keep consistency would be benefit for the community too

**Comment by sopelj** [comment]
Since [WAZO-3283](https://wazo-dev.atlassian.net/browse/WAZO-3283) was completed I updated this branch with the recommended conigs from [WAZO-3493](https://wazo-dev.atlassian.net/browse/WAZO-3493)

**Review by sduthil — APPROVED** [review]

**Comment by sduthil** [comment]
Thanks a lot Jesse! Feels cleaner now :)

**Comment by sopelj** [comment]
> Thanks a lot Jesse! Feels cleaner now :)

Thanks!

**Pull request merged**
